In [49]:
import numpy as np

In [50]:
data = np.genfromtxt('winequality-red.csv', delimiter=';', skip_header = True)

In [51]:
x = data[:, :-1]

In [52]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [53]:
y = data[:, -1]

In [54]:
y

array([5., 5., 5., ..., 6., 5., 6.])

In [55]:
from osl_linearregression import OLSLinearRegression

In [56]:
ols_lr = OLSLinearRegression()

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [59]:
ols_lr.train(x_train, y_train)

In [60]:
y_pred = ols_lr.predict(x_test)

In [61]:
y_pred

array([6.01088431, 5.90923329, 5.02192204, 5.82666313, 5.3909537 ,
       5.14672772, 5.46307608, 5.24444597, 5.75126592, 5.71696317,
       6.12280109, 5.11643294, 5.83802871, 6.20016752, 4.90306151,
       5.15844351, 5.64098029, 5.73365719, 5.09713996, 6.06152533,
       6.49007578, 5.12716223, 5.64442869, 5.78011111, 4.97106057,
       4.27789496, 5.49308535, 6.40472067, 6.29167627, 5.30596056,
       5.59674892, 5.80468214, 5.20340868, 6.11792249, 5.99980424,
       6.46819585, 5.91507295, 5.35529738, 5.44004636, 5.88242235,
       6.35811056, 6.61094133, 5.34552807, 5.10094713, 5.18112799,
       5.72991292, 5.65837951, 5.67896328, 5.52821673, 5.8633034 ,
       5.14606528, 5.39955672, 5.88242235, 5.42369938, 5.02637036,
       5.75009769, 5.90310219, 5.27205463, 5.58414615, 5.10797288,
       5.14391532, 6.40386733, 6.10147119, 5.73113467, 5.22806063,
       4.81252355, 5.7196468 , 5.76947396, 5.54042935, 5.53036966,
       5.16631793, 5.27493839, 5.42169223, 6.14996863, 5.27493

In [62]:
from sklearn.metrics import mean_squared_error

In [63]:
mse = mean_squared_error(y_test, y_pred)

In [64]:
mse

0.4497636316103533

In [65]:
y_train_pred = ols_lr.predict(x_train)

In [66]:
mse_train = mean_squared_error(y_train, y_train_pred)

In [67]:
mse

0.4497636316103533

In [68]:
from sklearn.metrics import mean_absolute_error

In [69]:
mae = mean_absolute_error(y_test, y_pred)

In [70]:
mae

0.5279214631205402

In [88]:
from gd_linearregression import GDLinearRegression

In [91]:
gd_lr = GDLinearRegression()

In [92]:
gd_lr.n_iter = 3000
gd_lr.eta = 0.001 
gd_lr.tol = 0.00001 

In [93]:
gd_lr.train(x_train, y_train)

   0 loss: 19.412661101963916
   1 loss: 94.60395737403132


In [94]:
gd_lr.eta = 0.0001

In [95]:
gd_lr.train(x_train, y_train)

   0 loss: 15.54641747050107
   1 loss: 11.263724892301017
   2 loss: 9.516001330006244
   3 loss: 8.761170459147817
   4 loss: 8.395928464935807
   5 loss: 8.184234015116562
   6 loss: 8.033724809524498
   7 loss: 7.908248316132912
   8 loss: 7.793642454163024
   9 loss: 7.684348469217955
  10 loss: 7.578173679954734
  11 loss: 7.474242578977586
  12 loss: 7.3721952666603165
  13 loss: 7.271873860745259
  14 loss: 7.173199809610651
  15 loss: 7.076125890062424
  16 loss: 6.9806174229460725
  17 loss: 6.88664491930819
  18 loss: 6.794181198454496
  19 loss: 6.703200255571365
  20 loss: 6.613676813891017
  21 loss: 6.525586144746856
  22 loss: 6.438903992516131
  23 loss: 6.353606540679248
  24 loss: 6.269670394046189
  25 loss: 6.1870725673878955
  26 loss: 6.105790476652143
  27 loss: 6.02580193126781
  28 loss: 5.947085126950888
  29 loss: 5.869618638781388
  30 loss: 5.793381414459439
  31 loss: 5.718352767703462
  32 loss: 5.644512371774549
  33 loss: 5.571840253119613
  34 loss: 5

In [96]:
x.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311])

In [97]:
from sklearn.preprocessing import StandardScaler

In [98]:
ss = StandardScaler()

In [99]:
ss.fit(x_train)

StandardScaler()

In [100]:
x_train_std = ss.transform(x_train)

In [101]:
x_test_std = ss.transform(x_test)

In [102]:
x_train_std[:3]

array([[-0.75263951,  0.61939332, -1.28750861, -0.32188053, -0.42987891,
        -0.6675016 , -0.72630984,  0.14700477,  1.04368124,  0.08152666,
        -0.93652718],
       [ 0.35055722, -0.56989651,  0.94423791, -0.4536111 , -0.74992848,
        -0.95147104, -0.93771725, -1.01187941,  0.26292627,  0.26253527,
         1.92041057],
       [ 0.98925006, -0.28673227, -0.14568481,  0.07331118,  0.31690342,
        -0.28887568, -0.4545003 ,  1.72730138, -0.19251413, -0.58217155,
        -0.38357149]])

In [103]:
x_test_std[:3]

array([[-6.94576520e-01,  1.24235466e+00, -1.33940969e+00,
        -2.56015246e-01, -6.00572016e-01, -4.78188636e-01,
        -8.77315136e-01, -2.26558138e+00,  5.23177928e-01,
        -1.54755077e+00,  2.19688841e+00],
       [ 1.10537603e+00, -6.83162213e-01,  8.40435748e-01,
        -2.56015246e-01,  4.87596520e-01, -4.78188636e-01,
        -3.03495007e-01,  2.94499124e-01, -9.73269096e-01,
         8.15266633e-02,  3.53702768e-01],
       [ 2.17930777e-03,  8.17608293e-01, -4.18826424e-02,
        -3.21880532e-01, -6.71560670e-02, -4.78188636e-01,
        -1.22288651e-01,  4.63064095e-01,  2.67461488e-03,
        -7.63180154e-01, -1.12084575e+00]])

In [104]:
gd_lr = GDLinearRegression()

In [105]:
gd_lr.n_iter = 3000
gd_lr.eta = 0.05
gd_lr.tol = 0.00001

In [106]:
gd_lr.train(x_train_std, y_train)

   0 loss: 32.29822115695671
   1 loss: 29.17477914369514
   2 loss: 26.358526322881147
   3 loss: 23.819019758718238
   4 loss: 21.528876243821202
   5 loss: 19.46345672286058
   6 loss: 17.60058479305193
   7 loss: 15.920295310720073
   8 loss: 14.404609650878058
   9 loss: 13.037334606799405
  10 loss: 11.80388229239707
  11 loss: 10.691108732671795
  12 loss: 9.687169105301376
  13 loss: 8.781387836723967
  14 loss: 7.964141964640678
  15 loss: 7.22675636051295
  16 loss: 6.561409564318753
  17 loss: 5.961049122852661
  18 loss: 5.419315444962212
  19 loss: 4.930473294619954
  20 loss: 4.489350137590259
  21 loss: 4.091280641317875
  22 loss: 3.7320567019510085
  23 loss: 3.407882438320834
  24 loss: 3.115333651265983
  25 loss: 2.851321298805734
  26 loss: 2.6130585840992997
  27 loss: 2.3980312945485065
  28 loss: 2.203971067387919
  29 loss: 2.0288312901665932
  30 loss: 1.8707653741021577
  31 loss: 1.7281071647689954
  32 loss: 1.5993532783094186
  33 loss: 1.483147172630251
 

In [107]:
y_pred = gd_lr.predict(x_test_std)

In [108]:
mse = mean_squared_error(y_test, y_pred)

In [109]:
mse

0.4507839261035078

In [110]:
mae = mean_absolute_error(y_test, y_pred)

In [111]:
mae

0.5279721806775306